<?php

namespace PhalconExt\Tests\Validation\Validator;

use PhalconExt\Validation\Validator\Color;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-26 at 05:16:28.
 */
class ColorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PhalconExt\Validation\Validator\Color::validate
     */
    public function testValidateTrue()
    {
        $validator1 = new Color(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('#fff'));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('#c0Fa98'));

        $this->assertTrue($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\Color::validate
     */
    public function testValidateFalse()
    {
        $validator1 = new Color(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('#4444'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('#rt745a'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('aaa'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(101010));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(10.5));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(array(1, 2, 3)));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\Color::validate
     */
    public function testValidateAllowEmptyTrue()
    {
        $validator1 = new Color(array(
            'message' => 'validation message',
            'allowEmpty' => true
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(''));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(false));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(null));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(0));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('0'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(array()));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\Color::validate
     */
    public function testValidateAllowEmptyFalse()
    {
        $validator1 = new Color(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(''));
        $mock->expects($this->once())
            ->method('appendMessage');

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(false));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(null));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(0));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('0'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(array()));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

}
