<?php

namespace PhalconExt\Tests\Validation\Validator;

use PhalconExt\Validation\Validator\EmailDomain;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-03-23 at 22:33:42.
 */
class EmailDomainTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers PhalconExt\Validation\Validator\EmailDomain::validate
     */
    public function testValidateTrue()
    {
        $validator1 = new EmailDomain(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('david.hubner@gmail.com'));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('petr@email.cz'));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('mailbox@yahoo.com'));

        $this->assertTrue($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\EmailDomain::validate
     */
    public function testValidateFalse()
    {
        $validator1 = new EmailDomain(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('some@really-not-exist.com'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('mail@domain.aaaa'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue('Not email'));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(array(1, 2, 3)));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\EmailDomain::validate
     */
    public function testValidateAllowEmptyTrue()
    {
        $validator1 = new EmailDomain(array(
            'message' => 'validation message',
            'allowEmpty' => true
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(''));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(false));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(null));

        $this->assertTrue($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(0));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

    /**
     * @covers PhalconExt\Validation\Validator\EmailDomain::validate
     */
    public function testValidateAllowEmptyFalse()
    {
        $validator1 = new EmailDomain(array(
            'message' => 'validation message',
            'allowEmpty' => false
        ));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(''));
        $mock->expects($this->once())
            ->method('appendMessage');

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(false));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(null));

        $this->assertFalse($validator1->validate($mock, 'attribute'));

        $mock = $this->getMock('Phalcon\Validation');
        $mock->expects($this->once())
            ->method('getValue')
            ->withAnyParameters()
            ->will($this->returnValue(0));

        $this->assertFalse($validator1->validate($mock, 'attribute'));
    }

}
